spring:
  data:
    redis:
      host: 139.224.1.155
      port: 6379
      database: 15
      timeout: 5s
      lettuce:
        pool:
          max-active: -1
          max-idle: 400
          min-idle: 0
      password: comma-redis
